### ISSUE TITLE
Exception in callback of async function: TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by SimonSimCity** [Meteor-Community-Packages/meteor-publish-composite#130]
I found the following exception which was reported in my logs a few days ago:

```
2020-03-23T17:37:29.242761535Z Exception in callback of async function: TypeError: Converting circular structure to JSON
2020-03-23T17:37:29.242791436Z     at JSON.stringify (<anonymous>)
2020-03-23T17:37:29.242796436Z     at PublishedDocumentList.addChildPub (packages/reywood:publish-composite/lib/published_document_list.js:27:32)
2020-03-23T17:37:29.242800436Z     at Publication.createChildPublication (packages/reywood:publish-composite/lib/publication.js:98:32)
2020-03-23T17:37:29.242804336Z     at Array.forEach (<anonymous>)
2020-03-23T17:37:29.242808436Z     at Function._.each._.forEach (packages/underscore.js:139:11)
2020-03-23T17:37:29.242812236Z     at Publication._publishChildrenOf (packages/reywood:publish-composite/lib/publication.js:96:11)
2020-03-23T17:37:29.242816036Z     at observeHandle.cursor.observe.added.Meteor.bindEnvironment.doc (packages/reywood:publish-composite/lib/publication.js:45:26)
2020-03-23T17:37:29.242820236Z     at runWithEnvironment (packages/meteor.js:1286:24)
2020-03-23T17:37:29.242824036Z     at Object.added (packages/meteor.js:1299:14)
2020-03-23T17:37:29.242827736Z     at _CachingChangeObserver.added (packages/minimongo/local_collection.js:1305:28)
2020-03-23T17:37:29.242831336Z     at added (packages/minimongo/local_collection.js:707:29)
2020-03-23T17:37:29.242835336Z     at runWithEnvironment (packages/meteor.js:1286:24)
2020-03-23T17:37:29.242839337Z     at packages/meteor.js:1299:14
2020-03-23T17:37:29.242843437Z     at packages/cultofcoders:redis-oplog/lib/mongo/ObserveMultiplex.js:256:18
2020-03-23T17:37:29.242847437Z     at _IdMap.forEach (packages/id-map/id-map.js:51:35)
2020-03-23T17:37:29.242851037Z     at ObserveMultiplexer._sendAdds (packages/cultofcoders:redis-oplog/lib/mongo/ObserveMultiplex.js:249:26)
2020-03-23T17:37:29.242854937Z     at packages/cultofcoders:redis-oplog/lib/mongo/ObserveMultiplex.js:68:18
2020-03-23T17:37:29.242858537Z     at runWithEnvironment (packages/meteor.js:1286:24)
2020-03-23T17:37:29.242862237Z     at Object.task (packages/meteor.js:1299:14)
2020-03-23T17:37:29.242865837Z     at Meteor._SynchronousQueue.SQp._run (packages/meteor.js:917:16)
2020-03-23T17:37:29.242895037Z     at packages/meteor.js:894:12
```

I cannot really say yet where it came from or how the subscription looked like where this error was thrown, but I found it useful to add it here for the record, if someone else runs into this problem. It should at least be investigated here, because it was thrown as a direct result of something this extension did - maybe in connection with another extension.

**Comment by drone1** [comment]
Just an educated guess, but are you publishing a composite with circular references?

**Comment by SimonSimCity** [comment]
Meehh ... you can also shoot yourself into the foot - that works as well ...

The error here is because I added additional debug information to the bug https://github.com/Meteor-Community-Packages/meteor-publish-composite/issues/38#issuecomment-564896571 which called `JSON.stringify(publication)` - and - apparently - the data in `publication` has a circular reference.
